name: Deploy

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Connect to Tailscale
        uses: tailscale/github-action@v4
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          tags: tag:github-actions

      - name: Create release directory
        run: |
          ssh \
            -i ${{ secrets.DEPLOY_SSH_KEY }} \
            ${{ secrets.DEPLOY_USER}}@${{ secrets.DEPLOY_HOST}} \
            "mkdir -p /var/www/bwilliams.net/releases/${GITHUB_REF_NAME}"

      - name: Upload website
        run: |
          rsync -az --delete \
            -e "ssh -i ~/.ssh/deploy_key" \
            --exclude=".git/" \
            --exclude=".github/" \
            ./ \
            ${{ secrets.DEPLOY_USER}}@${{ secrets.DEPLOY_HOST}}:/var/www/bwilliams.net/releases/${GITHUB_REF_NAME}/

      - name: Activate release
        run: |
          ssh \
            -i ~/.ssh/deploy_key \
            ${{ secrets.DEPLOY_USER}}@${{ secrets.DEPLOY_HOST}} \
            "ln -sfn releases/${GITHUB_REF_NAME} /var/www/bwilliams.net/current"